version       0.12
password      NUKyNCCLvgLH.
promote_date  v Stvrtok 4 April 2002 o 06:42pm
times         848430018 18578 3 831563811
levels        0 1 12 0
general       -1 0 0 1 1 0 829
user_set      1 1 1 1 0 0 0 1 1 #UNSET 1
fighting      0 0 0 0 6 10 1000 3000
purging       0 999999999
last_site     localhost procesor
mail_verify   #EMAILSET
description   is Mr Big
in_phrase     bounces in
out_phrase    rools and tumbles out
email         fred@localhost
homepage      #UNSET
recap_name    Fred
prompt        
nick_grm      Freda Fredovi Freda Fredom Fredom Fredov Fredova Fredovo
pueblo        1 1 1
restrict      ..............
ign_word
