version       0.11
password      NUKyNCCLvgLH
promote_date  on Utorok 19th November 1996 at 19:00pm
times         848430018 18578 3 831563811
levels        12 1 0 0
general       -1 0 0 -1 1 1 0 829 0
user_set      1 1 0 23 1 1 1 0 0 0 1 1 #UNSET
user_ignores  0 0 0 0 0 0 0 0 0 0
fighting      0 0 0 0 6 10
purging       0 9999999999
last_site     spirit
mail_verify   #EMAILSET
description   is Mr Big
in_phrase     bounces in
out_phrase    rools and tumbles out
email         fred@localhost
homepage      #UNSET
recap_name    Fred
prompt        ~OL$T~FT>~RS
nick_grm      Freda Fredovi Freda Fredom Fredom
pueblo        1 1 1
restrict      ..............
ign_word      
